---
title: "Day Seventeen: Institutional Incentives"
subtitle: "SDS 237: Data Ethnography"
author: "Lindsay Poirier"
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


## Take some time to free write on where your heart is at, and what energy you are bringing into class today. 

---

## Turn to a neighbor and discuss:

- What are some things you are doing or would like to do to navigate an emotionally charged time?

---

# Reading Discussion

---

## Audit Culture

- Cultural shift often understood to emerge/expand around the 1990s 
- Reliance on metrics to measure and rank performance
- Reliance on metrics to monitor and oversee individuals/institutions
- Redefines what accountability and governance mean

---

## Example: NYC CompStat

- Crime reduction strategy instituted in NYC in the 1990s
- Used crime and deployment data as performance metrics
- Officers penalized for failing to reduce crimes

---

## Example: Toxic Release Inventory

- US industrial facilities required to report amounts of toxic emissions they release into environment or transfer off-site
- Used to environmental burdens and injustices
- Used in journalism, activism, and legal proceedings

---

## Metric Fixation

- Tendencies to focus more on improving numbers than on actual performance/change
- Can incentivize individuals to engage in practices contrary to their goals
  - "Teaching to the test"
  - Surgeons not taking risky cases
- Can incentivize individuals to engage in deceptive reporting
  - Juking the Stats
  - Cooking the Books
  - Phantom Emissions 


---

# How should we understand the role of the individual vs. the institution when it comes to metric fixation?


