---
title: "Day Twelve: Participant Observation"
subtitle: "SDS 237: Data Ethnography"
author: "Lindsay Poirier"
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


## Think about a measurement you took in the past two weeks. How did you engage your body when taking that measurement?

---

## Turn to a neighbor and discuss:

1. How would you characterize the role and importance of your body in taking that measurement?

---

# Reading Discussion

---

## Cartesian Dualism

- Western philosophy conceptualizes body as essentially biological
  - Often perceived as closer to nature (further from culture)
- Rene Descartes: conceptualized mind/body distinct and separate
  - Mind: non-physical or non-material, associated with consciousness, thought, and self-awareness
  - Separate from brain: material human sensory organ

---

## Feminist Critiques of Cartesian Dualism

-   Mind and mental capacity often gets associated with masculinity
-   Physical and natural body often gets associated with femininity
-   Female bodies often perceived as closer to Nature
    -   "Mother Earth" vs. Man
    -   "virgin water" or "virgin forests"
    -   Nature itself is often feminized
    
---

## Embodiment

-   Around 1980s, feminist scholarship in anthropology, sociology, etc shifted
    -   Not just studies of the body, 
    -   Studies of how experiences living in bodies shape how we move through the world and what we perceive
    -   Also study the symbolic meaning we inscribe on bodies
-   Body not just biological but experiences are *embodied*
-   Critiqued essentialism about bodies - the idea that a set of characteristics define the "essence" of a body
    -   No singular characteristics to separate a "normal" body from an abnormal body
    -   No singular characteristics to separate a body from machines
    
---

# Why might feminist scholars call on us to view data practices as embodied?

---

## What is participant observation?

- An ethnographic method that involves embedding oneself in a community's day-to-day activities
- Ethnographer observes how people behave and interact through participation
- Ethnographer takes written notes on what they observe which are later elaborated

---

## When do ethnographers do participant observation?

- To figure out what kinds of interview questions to ask
- To place checks on what people say during interviews
- To gather details about the physical and social environments in which individuals engage
- To deepen the ethnographer's understanding of social contexts

---

## What gets recorded in participant observation?

- Details about:
  - The physical setting
  - The quantity and demographics of participants
  - Their physical appearance (such as attire)
  - Their traffic
  - The tools they use and/or exchange
  - Their physical movements
  - The way they communicate with one another
  - ...and more. 

---

# What might be some disadvantages to this method?

---

## Ethical Guidelines

- When should you announce yourself?
- Do you need informed consent?
- When is it advisable to identify participants?
- How should I behave in the space?

---

## Tips for Taking Field Notes

- Record the date, time, and place of data collection
- Record as much detail as you can about what you *observe*
- Leave space in notes to expand later
- Use abbreviations and shorthand when possible
- Create maps and graphics to help you remember details

---

## Expanding Field Notes

- Schedule a time to do it shortly after observation
- Convert your notes into a descriptive narrative
- Layer interpretations of your observations

---

<iframe width="560" height="315" src="https://www.youtube.com/embed/Gy9vam3tusk?si=sZYY1plJ4iKx8GPj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

