---
title: "Day Nineteen: Mobilizing Meaning"
subtitle: "SDS 237: Data Ethnography"
author: "Lindsay Poirier"
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


## What does the following statement mean to you?

> On April 10, 2023 at 9AM Northampton’s reported AQI was 54.


---

## Turn to a neighbor and discuss:

- What information do we need to be able to interpret the meaning of the number 54 in the following slide?

---

# Today's Topic: How do numbers acquire meaning? Through what means do we determine their significance?

---

# Reading Discussion

---

## Some Terminology in Semiotics

- Signifier: a material thing that signfies something else (e.g. a number, an word, an expression)
- Signified: a concept that the signifier represents
- Indexical: cases where the signifier is assumed to have a direct causal relationship with the signified
  - e.g. My dog's tail wag signifies that she is happy.
  - e.g. 5 signifies the number of fingers on my hand.
- Symbolic: cases where is the signifier takes on meaning through culturally-specific interpretation of the signified  

---

## Framing Statistics: Comparison/Ranking

- Is x more/less than y?
  - e.g. "Women make 77 cents for every dollar a man makes."
  - e.g. "The U.S. ranks first in firearm homicides in high income countries, with a rate of 4.52 firearm homicides per 100,000 population."

---

## Framing Statistics: Standards-setting/Benchmarking

- Identifying the yardstick to indicate "good" or "healthy"
  - e.g. "A credit score of 800 or above is 'excellent'."
  - e.g. "An AQI of 202 is 'very unhealthy'."
  
---

## Free-writing: Consider a **numeric** metric you use to measure something about yourself. Pick something that has special meaning for you. Is there a number that you strive for? How do you know when your score is "good"?

---

## Principles for Active Listening

1. Suspend judgment
2. Be curious
3. Halt internal commentary
4. Listen with intention
5. Express gratitude for sharing

---

## Structured Story-tellling

1. Find a partner, and decide who will speak first and who will speak second.
2. Two minutes:
  - First speaker: Provides uninterrupted narration about this measure. What does it mean to you? How did it come to have its meaning? How do you decide what success looks like?
  - Second speaker: Listens with intention: What does this number mean to this person?
3. One minute:
  - Second speaker: Reflect back on what you heard/ask questions, etc. (e.g. "From what I understand...")
  - First speaker: Affirm, correct, clarify, but also listen for what they heard
4. Swap and repeat. 

::: .notes

- Through what mechanisms did people decide what was good?
- Did you identify social structures at play in making this number meaningful?
- Did you hear your partner talk about ways this number might mean different things to different people?

:::

---

## Mobilizing Data Narratives

- Mobilization refers to the processes by which people prepare something to be put to use or into action
- Stakeholders strategically engage in meaning-making activities around data
- Shapes societal interpretations of data


