---
title: "Day Twenty-One: Data Activism"
subtitle: "SDS 237: Data Ethnography"
author: "Lindsay Poirier"
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```



## Consider a time when you felt surveiled, misrespresented, or under-represented by a data system. How did you respond?

---

## Turn to a neighbor and discuss:

- What do you suppose the designers of this system believe about the data it's collecting?
- What would it look like to resist this system?

---

# Reading Discussion


---

## Social Movement Theory

- Sociological research that studies how social movements form, operate, sustain, and fizzle out
- Political Process Theory: suggests that certain political formations enable social movements to form and operate
  - Political opportunities
  - Mobilizing structures
  - Framing processes
  - Protest cycles
  - Repertoires of contention
- Resource Mobilization Theory: suggests that the ability to leverage certain resources enable social movements to mobilize
  - Materials resources, human resources, organizational resources, cultural resources, etc.

---

## Data Activism

- A range of practices that confront the politics of datafication
- May involve affirmative data action
- May involve resistance to data systems

---

## Mobilizing Data Narratives

- Mobilization refers to the processes by which people prepare something to be put to use or into action
- Stakeholders strategically engage in meaning-making activities around data
- Shapes societal interpretations of data

---

## Narrating Data

- Curating plot details and trajectories 
  - Choosing variables to report on
  - Choosing how to sequence statistics
- Engaging literary or rhetorical devices
  - Techniques of communication designed to evoke a reaction from the listener
- Identifying the sense-making tools
  - Visuals
  - Statistical terminology (e.g. "statistically significant")
  

---

## What story-telling elements bring the data in this ad to life?


<iframe width="560" height="315" src="https://www.youtube.com/embed/LaxlJXpwkzs?si=OeuEWfDtE7LiPCBb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


---

## What story-telling elements bring the data in this ad to life?

<iframe width="560" height="315" src="https://www.youtube.com/embed/4x8y58ThUrI?si=haNxx8O2vp1aL3q4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

---

## What story-telling elements bring the data in this ad to life?

<iframe width="560" height="315" src="https://www.youtube.com/embed/QcDrE5YvqTs?si=ev3nW9wdHu1kK41k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

---

## What story-telling elements bring the data in this ad to life?

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZZUrrpq9p2U?si=uOXnnrFV5nXCfMva" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

::: {.notes}

- Ad banned in 2023
- Emphasized the renewables at the expense of high-carbon initiatives (which make up bulk of Shell production)
- “We strongly disagree with the ASA’s decision, which could slow the UK’s drive towards renewable energy,” said a spokesperson for Shell. “People are already well aware that Shell produces the oil and gas they depend on today. When customers fill up at our petrol stations across the UK, it’s under the instantly recognisable Shell logo.”
- “However, they [are] unlikely to be aware of the details of this in relation to specific companies,” the ASA said. “Ads [are] therefore likely to mislead consumers if they [have] misrepresented the contribution that lower-carbon initiatives played, or would play in the near future, as part of the overall balance of a company’s activities.”

:::


---

> "The actual number of Americans jailed or imprisoned, about 2.3 million." - Matt Korostoff

> [https://mkorostoff.github.io/incarceration-in-real-numbers/](https://mkorostoff.github.io/incarceration-in-real-numbers/)


---

<iframe width="560" height="315" src="https://www.youtube.com/embed/Ph6kT34bh-k?si=3HDf42OaN90Og7Zv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


---

<iframe width="560" height="315" src="https://www.youtube.com/embed/I9_ws7onQb8?si=DAB643YzyldA5j9H" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

---

<iframe width="560" height="315" src="https://www.youtube.com/embed/xWhGp5WauY8?si=ebWMaQMaSfX99E8e&amp;start=492" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


