---
title: "Institutional Incentives"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Purpose and Instructions

This checkpoint aims to document the institutions involved in the production and shaping of your final project dataset.

## Part 1: Institution Mapping

Below create long lists of institutions involved in each phase of the dataset's production. You should do some research to track down the names of specific government offices, private companies, or other partners involved in each phase. You may think back to some of the organizations that people you identified in the "peopling the data" checkpoint worked for. Your list should be more specific than "news outlets" or "legislatures." 

### Data Infrastructure Creation

* 

### Data Collection

* 

### Data Cleaning

* 

### Data Aggregation

* 

### Data Analysis

* 

### Data Dissemination

* 

### Data Consumption

* 


## Part 2: Identify institutions

> Select **three** institutions from your list that appear to have the largest influence over the final configuration and scope of the data. The goal of this section is to determine how this institution incentizes people to behave in certain ways in relation to the data.

> Do some research on each organization. Peruse their websites, reading through their About pages, their mission statements, their history, etc. Do they have pages outlining the values and commitments that guide their work? What do those pages say? Search for your dataset on their webpages. Do you find any blog posts or statements?

> Perform a web search for the organization with your dataset in quotation marks (e.g. PhRMA "Open Payments"). Be sure to look at news articles, videos, and official statements. What has this institution said/how has this institution acted in relation to your dataset?

Write a profile (about 200 words) for each institution. Specific questions you might consider include:

* What is the institution's stated mission? How does this stated mission relate to their data work?
* Which people are members of/work for this institution? Is participation voluntary? 
* What benefits do people gain from membership in this institution? What are the drawbacks to being a member of this institution?
* Which other institutions is this institution beholden to? What does this institution gain by meeting the expectations of these other institutions? What do they lose by failing to meet those expectations?
* What public statements has the institution put out regarding the data? Do these statements differ from those that individuals have put out regarding the data?
* What interests does this institution have in how the data gets reported? What influence do they have over the shape of the data?
* What legal and ethical bodies and infrastructures oversee how this institution conducts their data work?
* How transparent is the institution's data work?
* What repercussions might this institution face if they were to mishandle the data?

### Institution 1:

**Fill response here.**

### Institution 2:

**Fill response here.**

### Institution 3:

**Fill response here.**