---
title: "Peopling the Data"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Purpose and Instructions

This checkpoint is adapted from an experimental ethnographic methods exercise designed by my Ph.D. advisor Kim Fortun (UCI, Anthropology). She called it "peopling a project." The goal will be to draw to the surface the (typically invisible) human labor behind this dataset. Complete parts 1 and 2 below. 

## Part 1: List stakeholders from relevant social groups

To start, create a long list of people that are implicated in the production, aggregation, or circulation of this dataset. It can be really difficult to find people associated with a data collection program. Here are three strategies for "peopling this dataset".

- Start at LinkedIn. Enter the name of your dataset in quotation marks (e.g. "National Bridge Inventory") in the search bar. What kind of positions come up? 
- Search Google News for your dataset in quotation marks. What kinds of people are quoted in news articles about the dataset?
- Search Twitter for your dataset in quotation marks. What kinds of people are tweeting about the dataset?
- Check to see if there is an organization chart for the agency that runs the dataset. Can you figure out where the dataset is managed, and who runs that program?

Two important notes:

* Your list should be specific. You should provide more specificity than "data collectors" or "government agency employees" for instance. Try to identify who the data collectors are and what roles at which government agencies are implicated in the data collection. 
* While you should be specific, you don't need to list actual human names. You might list a person's role (e.g. statistician at the EPA)
* Be careful not to confuse people with institutions. Congress, for instance, is an institution. Government is an institution. Identify and name a specific type of person within this institution for this exercise. 

1. 
2. 
3. 
4. 
5. 
6. 
7. 
8.
9.
10. 

## Part 2: Profile a social group

Select at least **three** listed social groups. Profile each group below by answering some combination of the questions belows. You should aim to write 200 words per social group. 

> I encourage you not to make assumptions about a particular social group, but to search for relevant literature, media, or data pertaining to this social group. To enrich this section of the document, you may find YouTube videos of these individuals at work or speaking at a conference or with a news anchor. Feel free to embed those in the Markdown. Alternatively, you might find training guides or protocols directed at these social groups. Or maybe you'll track down Glassdoor profiles that depict information about their jobs. You might also check out data published by the [Bureau of Labor Statistics](https://www.bls.gov/oes/current/oes_stru.htm#17-0000) about typical compensation for these jobs broken down by demographic indicators. Be sure to cite all sources.

* How are their bodies implicated in the production of the data? What senses do they engage in their work with the data? What kinds of movements and exertions must they make in relation to the data?
* What do their day-to-day jobs look like or entail?
* What kind of education or training do they have?
* What interest do they have in the data or incentives to report the data in a particular way?
* What kind of critical judgment calls must they make when producing, aggregating, or circulating the data? 
* How is the work and standpoints of these social groups valued or validated?
* What social norms or discourses guide how they engage with the data?
* What protocols or regulations are they required to abide by?
* How do people in this social group identify themselves?
* What is the demographic make-up of the social group?


### Social group 1:

**Fill your response here.**

### Social group 2:

**Fill your response here.**

### Social group 3:

**Fill your response here.**

