---
title: "Semiotic Analysis"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Purpose and Instructions

In this checkpoint, referencing data documentation, you will study the definitions underlying the dataset, considering issues such as - What counts as an observation? How are observations counted or measured? How are observations categorized? In other words, in this assignment you will be performing an ethnography of data infrastructure - considering how the standards used to produce this dataset implicates what kinds of narratives we can draw from the data. 

## Units of Observation

> Any time we count something in the world, we are not only engaging in a process of tabulation; we are also engaged in a process of defining. If I count the number of students in a class, I first have to define what counts as a student. If someone is auditing the class, do they count? If I, as the instructor, am learning from my students, do I count myself as a student? As I make decisions about how I’m going to define "student," those decisions impact the numbers that I produce. When I change my definition of "student," how I go about tabulating students also changes. Thus, as we prepare to count observations in a dataset, it is important to know how those observations are defined.

### What does each row in your dataset represent? 

In this dataset, each row is a _____. 

### How does that observation get defined in the data documentation? 

> Find a definition for your unit of observation in the data documentation and cite it (with a citation) below. 

**Fill your response here.**

### Develop a timeline for this definition.

> Do some research on the agency website to determine when this definition was established and how it has changed over time. List key dates, along with what happened to the definition on those dates below. 

1. 
2. 
3. 
4. 
5. 

### How do social groups talk about this definition?

> Search Google for the following: "what counts as a ______" Fill the blank with your unit of observation. For instance, if I was studying the National Bridge Inventory, I might type "what counts as a federal bridge". Read through articles from multiple stakeholder perspectives (i.e. not just agencies). Can you identify any controversies or ambiguities about "what counts"? What are those controversies/ambiguities, and why did they emerge?

**Fill your response here.**

### What potentially relevant concerns are left out of the data due to the scope of this definition?

**Fill your response here.**

------------------------------------------------

> There are two sets of questions below - one set specific for categorical variables, and one set specific for numeric variables. You should select what you consider to be the three most important variables for producing claims in your dataset and respond to the questions below. It can be any combination of categorical/numeric. (e.g. 3 categorical; 2 cateogorical and 1 numeric, etc.)

------------------------------------------------


## Categorical Variables (Skip if your dataset doesn't have categorical variables)

> Select a categorical variable in your dataset. Be sure to select a specific variable. 

### How do concepts get divided in that categorical variable? What are the possible terms?

**Fill response here.**

### Can you identify certain people or things that might not fit neatly into these categories?

**Fill response here.**

### Examine the residual categories

> Residual categories are the catch-all categories for those things not easily classified. (e.g. Other, Multiple, etc.) Who or what might fall into a residual category in this dataset? In other words, who or what gets othered through the categories?

**Fill response here.**

------------------------------------------------

## Numeric Variables (Skip if your dataset doesn't have numeric variables)

> Select a count or measurement in your dataset. Be sure to select a specific variable. 

### According to what standards are these numbers reported?

> Read the data documentation to learn how the numbers are generated. What standards must the data collectors following when generating the number?

**Fill response here.**

### Through what social processes were those definitions and standards agreed upon?

> Through Google searching, can you find information about how these standards of data collection were agreed upon?

**Fill response here.**